[options]
; ==============================================================================
; Odoo 16 Configuration
; ==============================================================================

; Paths & Admin
addons_path = /mnt/addons,/mnt/addons_hash_customs,/mnt/addons1,/mnt/enterprise,/mnt/ov16
data_dir = /etc/odoo
admin_passwd = Alfa008@@8899

; Database Connection Configuration
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo16_db_passwd
db_name = False
dbfilter = .*
db_sslmode = prefer
db_maxconn = 64

; HTTP & Proxy Services
http_interface = 0.0.0.0
http_port = 8069
gevent_port = 8072
proxy_mode = True
list_db = True

; Logging Configuration
logfile = /etc/odoo/odoo-server.log
log_level = info

; Development & Runtime
dev_mode = reload
